<?php

namespace Core;

use Core\Managers\GeneratorManager;
use Core\Managers\IslandManager;
use pocketmine\permission\PermissionAttachment;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\Config;
use poggit\libasynql\DataConnector;

class Main extends PluginBase {

    private DataConnector $database;
    private IslandManager $islandManager;
    private GeneratorManager $generatorManager;

    private static self $instance;

    private Config $groups;
    private Config $users;

    private Config $generatorConfig;


    public function onEnable(): void {
        parent::onEnable(); // TODO: Change the autogenerated stub

        $this->saveResource("groups.yml");
        $this->groups = new Config($this->getDataFolder() . "groups.yml", Config::YAML);
        $this->users = new Config($this->getDataFolder() . "users.yml", Config::YAML);

        @mkdir($this->getDataFolder());

        $this->saveDefaultConfig();

        // 1. Tworzymy kontener (wszystkie managery się tworzą)
        $container = new Container($this);

        // 2. Tworzymy Bootstrapa i przekazujemy mu plugin oraz kontener
        $bootstrap = new Bootstrap($this, $container);

        // 3. Rejestrujemy wszystko
        $bootstrap->registerManagers();
        $bootstrap->registerListeners();
        $bootstrap->registerTasks();

        $this->database->executeGeneric("skygen.generators.init", []);

        $this->islandManager->loadAllIslandsFromDatabase(function() {
           $this->generatorManager->loadGenerators($this->database, $this->islandManager);
        });
    }

    public function onDisable(): void {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    public static function getInstance(): Main {
        return self::$instance;
    }

    public function getGroupsConfig() : Config {
        return $this->groups;
    }

    public function getUsersConfig() : Config {
        return $this->users;
    }
}