<?php

namespace Core;

use pocketmine\plugin\PluginBase;

class Main extends PluginBase {

    public function onEnable(): void {
        parent::onEnable(); // TODO: Change the autogenerated stub
        // 1. Tworzymy kontener (wszystkie managery się tworzą)
        $container = new Container($this);

        // 2. Tworzymy Bootstrapa i przekazujemy mu plugin oraz kontener
        $bootstrap = new Bootstrap($this, $container);

        // 3. Rejestrujemy wszystko
        $bootstrap->registerManagers();
        $bootstrap->registerListeners();
        $bootstrap->registerTasks();
    }

    public function onDisable(): void {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }
}