<?php

namespace Core;

use pocketmine\plugin\PluginBase;

class Main extends PluginBase {

    public function onEnable(): void {
        parent::onEnable(); // TODO: Change the autogenerated stub

        $container = new Container($this);
        $bootstrap = new Bootstrap($this, $container);
        $bootstrap->registerManagers();
        $bootstrap->registerListeners();
    }

    public function onDisable(): void {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }
}